name: Automation_Databricks_Project_AirflowScheduled
description: test random description
version: 2.0.0
author: abhisheks+e2etests@prophecy.io
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/SQL_Composer_AirflowScheduled_Databricks:
    name: SQL_Composer_AirflowScheduled_Databricks
    description: Job DBT
    fabricUID: 15
    scheduler:
      Composer: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: '*/5 9-10 5 5 *'
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: true
    createdAt: '2025-05-05 09:31:03'
    author: abhisheks+e2etests@prophecy.io
    models: []
    sqlProjects:
    - '15772'
  jobs/SQL_MWAA_AirflowScheduled_Databricks:
    name: SQL_MWAA_AirflowScheduled_Databricks
    description: Job DBT
    fabricUID: 17
    scheduler:
      MWAA: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: '*/5 9-10 5 5 *'
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: true
    createdAt: '2025-05-05 09:32:19'
    author: abhisheks+e2etests@prophecy.io
    models: []
    sqlProjects:
    - '15772'
  jobs/SQL_PMAir_AirflowScheduled_Databricks:
    name: SQL_PMAir_AirflowScheduled_Databricks
    description: Job DBT
    fabricUID: 13
    scheduler:
      Prophecy: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: '*/5 9-10 5 5 *'
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: true
    createdAt: '2025-05-05 09:33:35'
    author: abhisheks+e2etests@prophecy.io
    models: []
    sqlProjects:
    - '15772'
  jobs/SQL_Databricks_Scheduled_Databricks:
    name: SQL_Databricks_Scheduled_Databricks
    description: Job DBT
    fabricUID: 9
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: prophecy_internal_jobs
    scheduleCron: 0 0/5 9-10 5 5 ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: true
    createdAt: '2025-05-05 09:34:51'
    author: abhisheks+e2etests@prophecy.io
    models: []
    sqlProjects: []
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-05-05 09:28:17'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/testModelSchdRun_Automation_Databricks_Project_AirflowScheduled:
    name: testModelSchdRun_Automation_Databricks_Project_AirflowScheduled
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: c_int64
        dataType:
          type: Integer
      - name: c_bignumeric
        dataType:
          type: Integer
      - name: c_string
        dataType:
          type: String
      - name: c_float64
        dataType:
          type: Float
      - name: c_bool
        dataType:
          type: String
    description: null
    author: abhisheks+e2etests@prophecy.io
    files:
    - models/testmodel/testModelSchdRun_Automation_Databricks_Project_AirflowScheduled.sql
    - .prophecy/ide/models/testModelSchdRun_Automation_Databricks_Project_AirflowScheduled.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2025-05-05 09:30:18'
sqlSnapshots: {}
sqlTests: {}
sqlMacros:
  .prophecy/metadata/sqlmacros/generate_schema_name:
    name: generate_schema_name
    macroType: expression
    description: null
    author: abhisheks+e2etests@prophecy.io
    files:
    - macros/generate_schema_name.sql
    - .prophecy/ide/macros/generate_schema_name.json
    createdAt: '2025-05-05 09:28:23'
sqlSeeds:
  .prophecy/metadata/sqlseeds/testSeedSchdRun_Automation_Databricks_Project_AirflowScheduled:
    name: testSeedSchdRun_Automation_Databricks_Project_AirflowScheduled
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: c_int64
        dataType:
          type: Integer
      - name: c_bignumeric
        dataType:
          type: Integer
      - name: c_string
        dataType:
          type: String
      - name: c_float64
        dataType:
          type: Float
      - name: c_bool
        dataType:
          type: String
    description: null
    author: abhisheks+e2etests@prophecy.io
    files:
    - seeds/testSeedSchdRun_Automation_Databricks_Project_AirflowScheduled.csv
    - seeds/seeds.yml
    createdAt: '2025-05-05 09:30:15'
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: abhisheks+e2etests@prophecy.io
  createdAt: '2025-05-05 09:28:17'
dependencies: []
projectDependencies:
  '13581':
    projectUID: 13581
    projectName: ProphecyDatabricksSqlBasics
    repositoryPath: gitUri=https://github.com/prophecy-io/databricks-sql-basics&subPath=
    version: 0.0.5.dev0
    isDefault: true
    author: null
    createdAt: '2025-05-05 09:27:57'
flags:
  shouldAddDefaultDependenciesIfAbsent: false
pipelineConfigurations: {}
